# Generated by Django 4.2.3 on 2023-07-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_cook_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="cook_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/"
            ),
        ),
    ]
