# Generated by Django 4.2.3 on 2023-07-22 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_cook_cook_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="cook_photo",
        ),
    ]
