# Generated by Django 4.2.3 on 2023-07-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0004_remove_cook_cook_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cooks/"),
        ),
    ]
