# Generated by Django 4.2.3 on 2023-07-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0005_cook_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="dish_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="dishes/"
            ),
        ),
    ]
