# Generated by Django 4.2.3 on 2023-07-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0007_alter_cook_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="dish_photo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
